### ISSUE TITLE
Wanting to visualise entire model file but issues with spread and layout, lag and SVG download

### ISSUE THREAD

**Issue by bananabenana** [pstjohn/d3flux#13]
Hi, first off wanted to say how cool this tool is. I can visualise sub-sections of models no problem, but when I try to visualise an entire model (say 1,700 reactions), I have 3 issues that don't allow proper vis:

1. The spread does not take up the full canvas size. So if I do 1000 x 1000, only the center of the image will be filled out, leaving the sides bare. Is there a way to modify layout behaviour?
2. This also generates massive lag within Jupyter notebook, which means I can't really properly visualise it, or move nodes etc. This also impacts my ability to:
3. SVG or JSON save. Is there a way to programmatically save, without clicking the widget? My current thought process is to direct output as object then save object as svg/json?

Thanks

**Comment by pstjohn** [comment]
Hey @bananabenana, thanks for the interest! 
To your points (1) and (2), I will say that the automated layout is mainly useful to get a start to a moderate-sized model, but every 'publication-quality' figure I've generated with this tool I've had to manually drag the points to a desired layout. (If you save the json of the model, the points where you've dragged are saved for the next time you generate the flux map). It's usually an iterative process, and you can use the 'background_template' argument to put in a grid or other guides to help layout the metabolites and reaction nodes.

Just a couple examples of images I've made (again, these are all laid out manually! 😄)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8350737/figure/F1/
https://www.sciencedirect.com/science/article/pii/S2542435119302545#fig2
https://journals.asm.org/doi/full/10.1128/AEM.00996-17#F1

Automatically generating an interpretable diagram for 1,700 reactions is a monumental task and not really what I set out to solve. They call them 'hairball' diagrams, maybe look for a different tool for the whole model that's designed for that goal (https://doi.org/10.1093/nar/gkaa409 ?)

For (3), unfortunately that's quite challenging -- I also would like the ability to do that, but javascript is not my strong suit... The library uses the browser to render the image, and running the javascript layout in a headless fashion is nontrivial. Maybe things have improved since the last time I looked into it? This is all based on an old version of D3.js, so that would be the place to look. Sorry for the bad news!

**Comment by bananabenana** [comment]
Hi @pstjohn, thanks for your fast response.

> To your points (1) and (2), I will say that the automated layout is mainly useful to get a start to a moderate-sized model, but every 'publication-quality' figure I've generated with this tool I've had to manually drag the points to a desired layout. (If you save the json of the model, the points where you've dragged are saved for the next time you generate the flux map). It's usually an iterative process, and you can use the 'background_template' argument to put in a grid or other guides to help layout the metabolites and reaction nodes.

Yes that makes sense, I understand. Thanks

> Just a couple examples of images I've made (again, these are all laid out manually! 😄)

They all look really nice, why I wanted to use the tool in the first place :)

> Automatically generating an interpretable diagram for 1,700 reactions is a monumental task and not really what I set out to solve. They call them 'hairball' diagrams, maybe look for a different tool for the whole model that's designed for that goal (https://doi.org/10.1093/nar/gkaa409 ?)

Makes total sense. Cheers for pointing me towards this tool, I will check it out!

> For (3), unfortunately that's quite challenging -- I also would like the ability to do that, but javascript is not my strong suit... The library uses the browser to render the image, and running the javascript layout in a headless fashion is nontrivial. Maybe things have improved since the last time I looked into it? This is all based on an old version of D3.js, so that would be the place to look. Sorry for the bad news!

Ah no worries.


Thanks again!
